-- V11: India Geographic Master Data — Country › States/UTs › Districts
-- Tables: geo_countries, geo_states, geo_districts
-- Scope: India only (28 States + 8 Union Territories, all districts)

-- ── Tables ────────────────────────────────────────────────────────────────────

CREATE TABLE geo_countries (
    id        SERIAL       PRIMARY KEY,
    code      VARCHAR(2)   NOT NULL UNIQUE,
    name_en   VARCHAR(100) NOT NULL,
    name_hi   VARCHAR(100) NOT NULL,
    is_active BOOLEAN      NOT NULL DEFAULT true
);

CREATE TABLE geo_states (
    id         SERIAL       PRIMARY KEY,
    country_id INTEGER      NOT NULL REFERENCES geo_countries(id),
    code       VARCHAR(5)   NOT NULL,
    name_en    VARCHAR(100) NOT NULL,
    name_hi    VARCHAR(100) NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT uq_geo_states_country_code UNIQUE (country_id, code)
);

CREATE TABLE geo_districts (
    id        SERIAL       PRIMARY KEY,
    state_id  INTEGER      NOT NULL REFERENCES geo_states(id),
    name_en   VARCHAR(100) NOT NULL,
    name_hi   VARCHAR(100) NOT NULL,
    is_active BOOLEAN      NOT NULL DEFAULT true
);

CREATE INDEX idx_geo_states_country  ON geo_states(country_id);
CREATE INDEX idx_geo_states_code     ON geo_states(code);
CREATE INDEX idx_geo_dist_state      ON geo_districts(state_id);
CREATE INDEX idx_geo_dist_name_en    ON geo_districts(name_en);

-- ── Country ───────────────────────────────────────────────────────────────────

INSERT INTO geo_countries (id, code, name_en, name_hi)
OVERRIDING SYSTEM VALUE VALUES
(1, 'IN', 'India', 'भारत');
SELECT setval('geo_countries_id_seq', 1, true);

-- ── States & Union Territories ────────────────────────────────────────────────
-- IDs 1-28: States | IDs 29-36: Union Territories

INSERT INTO geo_states (id, country_id, code, name_en, name_hi)
OVERRIDING SYSTEM VALUE VALUES
( 1, 1, 'AP', 'Andhra Pradesh',                           'आंध्र प्रदेश'),
( 2, 1, 'AR', 'Arunachal Pradesh',                        'अरुणाचल प्रदेश'),
( 3, 1, 'AS', 'Assam',                                    'असम'),
( 4, 1, 'BR', 'Bihar',                                    'बिहार'),
( 5, 1, 'CT', 'Chhattisgarh',                             'छत्तीसगढ़'),
( 6, 1, 'GA', 'Goa',                                      'गोवा'),
( 7, 1, 'GJ', 'Gujarat',                                  'गुजरात'),
( 8, 1, 'HR', 'Haryana',                                  'हरियाणा'),
( 9, 1, 'HP', 'Himachal Pradesh',                         'हिमाचल प्रदेश'),
(10, 1, 'JH', 'Jharkhand',                                'झारखंड'),
(11, 1, 'KA', 'Karnataka',                                'कर्नाटक'),
(12, 1, 'KL', 'Kerala',                                   'केरल'),
(13, 1, 'MP', 'Madhya Pradesh',                           'मध्य प्रदेश'),
(14, 1, 'MH', 'Maharashtra',                              'महाराष्ट्र'),
(15, 1, 'MN', 'Manipur',                                  'मणिपुर'),
(16, 1, 'ML', 'Meghalaya',                                'मेघालय'),
(17, 1, 'MZ', 'Mizoram',                                  'मिजोरम'),
(18, 1, 'NL', 'Nagaland',                                 'नागालैंड'),
(19, 1, 'OR', 'Odisha',                                   'ओडिशा'),
(20, 1, 'PB', 'Punjab',                                   'पंजाब'),
(21, 1, 'RJ', 'Rajasthan',                                'राजस्थान'),
(22, 1, 'SK', 'Sikkim',                                   'सिक्किम'),
(23, 1, 'TN', 'Tamil Nadu',                               'तमिलनाडु'),
(24, 1, 'TG', 'Telangana',                                'तेलंगाना'),
(25, 1, 'TR', 'Tripura',                                  'त्रिपुरा'),
(26, 1, 'UP', 'Uttar Pradesh',                            'उत्तर प्रदेश'),
(27, 1, 'UK', 'Uttarakhand',                              'उत्तराखंड'),
(28, 1, 'WB', 'West Bengal',                              'पश्चिम बंगाल'),
-- Union Territories
(29, 1, 'AN', 'Andaman and Nicobar Islands',              'अंडमान और निकोबार द्वीपसमूह'),
(30, 1, 'CH', 'Chandigarh',                               'चंडीगढ़'),
(31, 1, 'DH', 'Dadra and Nagar Haveli and Daman and Diu', 'दादरा और नगर हवेली और दमन और दीव'),
(32, 1, 'DL', 'Delhi',                                    'दिल्ली'),
(33, 1, 'JK', 'Jammu and Kashmir',                        'जम्मू और कश्मीर'),
(34, 1, 'LA', 'Ladakh',                                   'लद्दाख'),
(35, 1, 'LD', 'Lakshadweep',                              'लक्षद्वीप'),
(36, 1, 'PY', 'Puducherry',                               'पुदुच्चेरी');
SELECT setval('geo_states_id_seq', 36, true);

-- ── Districts ─────────────────────────────────────────────────────────────────
-- Inserted per state using explicit state_id (matches the IDs above).

-- 1. Andhra Pradesh (26 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(1, 'Alluri Sitharama Raju',    'अल्लूरी सीताराम राजू'),
(1, 'Anakapalli',               'अनकापल्ली'),
(1, 'Anantapur',                'अनंतपुर'),
(1, 'Bapatla',                  'बापतला'),
(1, 'Chittoor',                 'चित्तूर'),
(1, 'East Godavari',            'पूर्व गोदावरी'),
(1, 'Eluru',                    'एलुरु'),
(1, 'Guntur',                   'गुंटूर'),
(1, 'Kakinada',                 'काकीनाडा'),
(1, 'Konaseema',                'कोनसीमा'),
(1, 'Krishna',                  'कृष्णा'),
(1, 'Kurnool',                  'कुर्नूल'),
(1, 'Manyam',                   'मन्यम'),
(1, 'NTR',                      'एनटीआर'),
(1, 'Nandyal',                  'नंद्याल'),
(1, 'Nellore',                  'नेल्लोर'),
(1, 'Palnadu',                  'पालनाडु'),
(1, 'Prakasam',                 'प्रकाशम'),
(1, 'Sri Balaji',               'श्री बालाजी'),
(1, 'Sri Sathya Sai',           'श्री सत्य साई'),
(1, 'Srikakulam',               'श्रीकाकुलम'),
(1, 'Tirupati',                 'तिरुपति'),
(1, 'Visakhapatnam',            'विशाखापट्नम'),
(1, 'Vizianagaram',             'विजयनगरम'),
(1, 'West Godavari',            'पश्चिम गोदावरी'),
(1, 'YSR Kadapa',               'वाईएसआर कडप्पा');

-- 2. Arunachal Pradesh (26 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(2, 'Anjaw',                    'अंजाव'),
(2, 'Changlang',                'चांगलांग'),
(2, 'Dibang Valley',            'दिबांग घाटी'),
(2, 'East Kameng',              'पूर्व कामेंग'),
(2, 'East Siang',               'पूर्व सियांग'),
(2, 'Kamle',                    'कामले'),
(2, 'Kra Daadi',                'क्रा दाादी'),
(2, 'Kurung Kumey',             'कुरुंग कुमे'),
(2, 'Lepa Rada',                'लेपा राडा'),
(2, 'Lohit',                    'लोहित'),
(2, 'Longding',                 'लोंगडिंग'),
(2, 'Lower Dibang Valley',      'निचली दिबांग घाटी'),
(2, 'Lower Siang',              'निचला सियांग'),
(2, 'Lower Subansiri',          'निचला सुबनसिरि'),
(2, 'Namsai',                   'नामसाई'),
(2, 'Pakke-Kessang',            'पक्के-केसांग'),
(2, 'Papum Pare',               'पापुम पारे'),
(2, 'Shi Yomi',                 'शि योमी'),
(2, 'Siang',                    'सियांग'),
(2, 'Tawang',                   'तवांग'),
(2, 'Tirap',                    'तिरप'),
(2, 'Upper Dibang Valley',      'ऊपरी दिबांग घाटी'),
(2, 'Upper Siang',              'ऊपरी सियांग'),
(2, 'Upper Subansiri',          'ऊपरी सुबनसिरि'),
(2, 'West Kameng',              'पश्चिम कामेंग'),
(2, 'West Siang',               'पश्चिम सियांग');

-- 3. Assam (35 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(3, 'Bajali',                   'बजाली'),
(3, 'Baksa',                    'बक्सा'),
(3, 'Barpeta',                  'बारपेटा'),
(3, 'Biswanath',                'बिश्वनाथ'),
(3, 'Bongaigaon',               'बोंगाईगांव'),
(3, 'Cachar',                   'कछार'),
(3, 'Charaideo',                'चराईदेव'),
(3, 'Chirang',                  'चिरांग'),
(3, 'Darrang',                  'दरांग'),
(3, 'Dhemaji',                  'धेमाजी'),
(3, 'Dhubri',                   'धुबरी'),
(3, 'Dibrugarh',                'डिब्रूगढ़'),
(3, 'Dima Hasao',               'दिमा हसाओ'),
(3, 'Goalpara',                 'गोआलपाड़ा'),
(3, 'Golaghat',                 'गोलाघाट'),
(3, 'Hailakandi',               'हैलाकांदी'),
(3, 'Hojai',                    'होजाई'),
(3, 'Jorhat',                   'जोरहाट'),
(3, 'Kamrup',                   'कामरूप'),
(3, 'Kamrup Metropolitan',      'कामरूप महानगर'),
(3, 'Karbi Anglong',            'कार्बी आंगलोंग'),
(3, 'Karimganj',                'करीमगंज'),
(3, 'Kokrajhar',                'कोकराझार'),
(3, 'Lakhimpur',                'लखीमपुर'),
(3, 'Majuli',                   'माजुली'),
(3, 'Morigaon',                 'मोरीगांव'),
(3, 'Nagaon',                   'नगांव'),
(3, 'Nalbari',                  'नलबाड़ी'),
(3, 'Sivasagar',                'शिवसागर'),
(3, 'Sonitpur',                 'सोनितपुर'),
(3, 'South Salmara-Mankachar',  'दक्षिण सालमारा-मनकाचर'),
(3, 'Tamulpur',                 'तामुलपुर'),
(3, 'Tinsukia',                 'तिनसुकिया'),
(3, 'Udalguri',                 'उदलगुड़ी'),
(3, 'West Karbi Anglong',       'पश्चिम कार्बी आंगलोंग');

-- 4. Bihar (38 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(4, 'Araria',          'अररिया'),
(4, 'Arwal',           'अरवल'),
(4, 'Aurangabad',      'औरंगाबाद'),
(4, 'Banka',           'बांका'),
(4, 'Begusarai',       'बेगूसराय'),
(4, 'Bhagalpur',       'भागलपुर'),
(4, 'Bhojpur',         'भोजपुर'),
(4, 'Buxar',           'बक्सर'),
(4, 'Darbhanga',       'दरभंगा'),
(4, 'East Champaran',  'पूर्वी चंपारण'),
(4, 'Gaya',            'गया'),
(4, 'Gopalganj',       'गोपालगंज'),
(4, 'Jamui',           'जमुई'),
(4, 'Jehanabad',       'जहानाबाद'),
(4, 'Kaimur',          'कैमूर'),
(4, 'Katihar',         'कटिहार'),
(4, 'Khagaria',        'खगड़िया'),
(4, 'Kishanganj',      'किशनगंज'),
(4, 'Lakhisarai',      'लखीसराय'),
(4, 'Madhepura',       'मधेपुरा'),
(4, 'Madhubani',       'मधुबनी'),
(4, 'Munger',          'मुंगेर'),
(4, 'Muzaffarpur',     'मुजफ्फरपुर'),
(4, 'Nalanda',         'नालंदा'),
(4, 'Nawada',          'नवादा'),
(4, 'Patna',           'पटना'),
(4, 'Purnia',          'पूर्णिया'),
(4, 'Rohtas',          'रोहतास'),
(4, 'Saharsa',         'सहरसा'),
(4, 'Samastipur',      'समस्तीपुर'),
(4, 'Saran',           'सारण'),
(4, 'Sheikhpura',      'शेखपुरा'),
(4, 'Sheohar',         'शिवहर'),
(4, 'Sitamarhi',       'सीतामढ़ी'),
(4, 'Siwan',           'सीवान'),
(4, 'Supaul',          'सुपौल'),
(4, 'Vaishali',        'वैशाली'),
(4, 'West Champaran',  'पश्चिमी चंपारण');

-- 5. Chhattisgarh (33 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(5, 'Balod',                              'बालोद'),
(5, 'Baloda Bazar',                       'बलौदा बाजार'),
(5, 'Balrampur',                          'बलरामपुर'),
(5, 'Bastar',                             'बस्तर'),
(5, 'Bemetara',                           'बेमेतरा'),
(5, 'Bijapur',                            'बीजापुर'),
(5, 'Bilaspur',                           'बिलासपुर'),
(5, 'Dantewada',                          'दंतेवाड़ा'),
(5, 'Dhamtari',                           'धमतरी'),
(5, 'Durg',                               'दुर्ग'),
(5, 'Gariaband',                          'गरियाबंद'),
(5, 'Gaurela-Pendra-Marwahi',             'गौरेला-पेंड्रा-मरवाही'),
(5, 'Janjgir-Champa',                     'जांजगीर-चांपा'),
(5, 'Jashpur',                            'जशपुर'),
(5, 'Kabirdham',                          'कबीरधाम'),
(5, 'Kanker',                             'कांकेर'),
(5, 'Khairagarh-Chhuikhadan-Gandai',      'खैरागढ़-छुईखदान-गंडई'),
(5, 'Kondagaon',                          'कोंडागांव'),
(5, 'Korba',                              'कोरबा'),
(5, 'Koriya',                             'कोरिया'),
(5, 'Mahasamund',                         'महासमुंद'),
(5, 'Manendragarh-Chirmiri-Bharatpur',    'मनेंद्रगढ़-चिरमिरी-भरतपुर'),
(5, 'Mohla-Manpur-Ambagarh Chowki',       'मोहला-मानपुर-अंबागढ़ चौकी'),
(5, 'Mungeli',                            'मुंगेली'),
(5, 'Narayanpur',                         'नारायणपुर'),
(5, 'Raigarh',                            'रायगढ़'),
(5, 'Raipur',                             'रायपुर'),
(5, 'Rajnandgaon',                        'राजनांदगांव'),
(5, 'Sakti',                              'सक्ती'),
(5, 'Sarangarh-Bilaigarh',                'सारंगढ़-बिलाईगढ़'),
(5, 'Sukma',                              'सुकमा'),
(5, 'Surajpur',                           'सूरजपुर'),
(5, 'Surguja',                            'सरगुजा');

-- 6. Goa (2 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(6, 'North Goa', 'उत्तर गोवा'),
(6, 'South Goa',  'दक्षिण गोवा');

-- 7. Gujarat (33 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(7, 'Ahmedabad',        'अहमदाबाद'),
(7, 'Amreli',           'अमरेली'),
(7, 'Anand',            'आणंद'),
(7, 'Aravalli',         'अरावली'),
(7, 'Banaskantha',      'बनासकांठा'),
(7, 'Bharuch',          'भरूच'),
(7, 'Bhavnagar',        'भावनगर'),
(7, 'Botad',            'बोटाद'),
(7, 'Chhota Udaipur',   'छोटा उदयपुर'),
(7, 'Dahod',            'दाहोद'),
(7, 'Dang',             'डांग'),
(7, 'Devbhoomi Dwarka', 'देवभूमि द्वारका'),
(7, 'Gandhinagar',      'गांधीनगर'),
(7, 'Gir Somnath',      'गिर सोमनाथ'),
(7, 'Jamnagar',         'जामनगर'),
(7, 'Junagadh',         'जूनागढ़'),
(7, 'Kheda',            'खेड़ा'),
(7, 'Kutch',            'कच्छ'),
(7, 'Mahisagar',        'महीसागर'),
(7, 'Mehsana',          'मेहसाणा'),
(7, 'Morbi',            'मोरबी'),
(7, 'Narmada',          'नर्मदा'),
(7, 'Navsari',          'नवसारी'),
(7, 'Panchmahal',       'पंचमहल'),
(7, 'Patan',            'पाटण'),
(7, 'Porbandar',        'पोरबंदर'),
(7, 'Rajkot',           'राजकोट'),
(7, 'Sabarkantha',      'साबरकांठा'),
(7, 'Surat',            'सूरत'),
(7, 'Surendranagar',    'सुरेंद्रनगर'),
(7, 'Tapi',             'तापी'),
(7, 'Vadodara',         'वडोदरा'),
(7, 'Valsad',           'वलसाड');

-- 8. Haryana (22 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(8, 'Ambala',          'अंबाला'),
(8, 'Bhiwani',         'भिवानी'),
(8, 'Charkhi Dadri',   'चरखी दादरी'),
(8, 'Faridabad',       'फरीदाबाद'),
(8, 'Fatehabad',       'फतेहाबाद'),
(8, 'Gurugram',        'गुरुग्राम'),
(8, 'Hisar',           'हिसार'),
(8, 'Jhajjar',         'झज्जर'),
(8, 'Jind',            'जींद'),
(8, 'Kaithal',         'कैथल'),
(8, 'Karnal',          'करनाल'),
(8, 'Kurukshetra',     'कुरुक्षेत्र'),
(8, 'Mahendragarh',    'महेंद्रगढ़'),
(8, 'Nuh',             'नूंह'),
(8, 'Palwal',          'पलवल'),
(8, 'Panchkula',       'पंचकूला'),
(8, 'Panipat',         'पानीपत'),
(8, 'Rewari',          'रेवाड़ी'),
(8, 'Rohtak',          'रोहतक'),
(8, 'Sirsa',           'सिरसा'),
(8, 'Sonipat',         'सोनीपत'),
(8, 'Yamunanagar',     'यमुनानगर');

-- 9. Himachal Pradesh (12 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(9, 'Bilaspur',         'बिलासपुर'),
(9, 'Chamba',           'चंबा'),
(9, 'Hamirpur',         'हमीरपुर'),
(9, 'Kangra',           'कांगड़ा'),
(9, 'Kinnaur',          'किन्नौर'),
(9, 'Kullu',            'कुल्लू'),
(9, 'Lahaul and Spiti', 'लाहौल और स्पीति'),
(9, 'Mandi',            'मंडी'),
(9, 'Shimla',           'शिमला'),
(9, 'Sirmaur',          'सिरमौर'),
(9, 'Solan',            'सोलन'),
(9, 'Una',              'ऊना');

-- 10. Jharkhand (24 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(10, 'Bokaro',                'बोकारो'),
(10, 'Chatra',                'चतरा'),
(10, 'Deoghar',               'देवघर'),
(10, 'Dhanbad',               'धनबाद'),
(10, 'Dumka',                 'दुमका'),
(10, 'East Singhbhum',        'पूर्वी सिंहभूम'),
(10, 'Garhwa',                'गढ़वा'),
(10, 'Giridih',               'गिरिडीह'),
(10, 'Godda',                 'गोड्डा'),
(10, 'Gumla',                 'गुमला'),
(10, 'Hazaribagh',            'हजारीबाग'),
(10, 'Jamtara',               'जामताड़ा'),
(10, 'Khunti',                'खूंटी'),
(10, 'Koderma',               'कोडरमा'),
(10, 'Latehar',               'लातेहार'),
(10, 'Lohardaga',             'लोहरदगा'),
(10, 'Pakur',                 'पाकुड़'),
(10, 'Palamu',                'पलामू'),
(10, 'Ramgarh',               'रामगढ़'),
(10, 'Ranchi',                'रांची'),
(10, 'Sahebganj',             'साहिबगंज'),
(10, 'Seraikela Kharsawan',   'सरायकेला खरसावां'),
(10, 'Simdega',               'सिमडेगा'),
(10, 'West Singhbhum',        'पश्चिमी सिंहभूम');

-- 11. Karnataka (31 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(11, 'Bagalkote',          'बागलकोट'),
(11, 'Ballari',            'बल्लारी'),
(11, 'Belagavi',           'बेलगावी'),
(11, 'Bengaluru Rural',    'बेंगलुरु ग्रामीण'),
(11, 'Bengaluru Urban',    'बेंगलुरु शहरी'),
(11, 'Bidar',              'बीदर'),
(11, 'Chamarajanagar',     'चामराजनगर'),
(11, 'Chikkaballapura',    'चिक्कबल्लापुर'),
(11, 'Chikkamagaluru',     'चिक्कमगलुरु'),
(11, 'Chitradurga',        'चित्रदुर्ग'),
(11, 'Dakshina Kannada',   'दक्षिण कन्नड'),
(11, 'Davanagere',         'दावणगेरे'),
(11, 'Dharwad',            'धारवाड'),
(11, 'Gadag',              'गदग'),
(11, 'Hassan',             'हासन'),
(11, 'Haveri',             'हावेरी'),
(11, 'Kalaburagi',         'कलबुर्गी'),
(11, 'Kodagu',             'कोडागु'),
(11, 'Kolar',              'कोलार'),
(11, 'Koppal',             'कोप्पल'),
(11, 'Mandya',             'मांड्या'),
(11, 'Mysuru',             'मैसूरु'),
(11, 'Raichur',            'रायचूर'),
(11, 'Ramanagara',         'रामनगर'),
(11, 'Shivamogga',         'शिवमोग्गा'),
(11, 'Tumakuru',           'तुमकुरु'),
(11, 'Udupi',              'उडुपी'),
(11, 'Uttara Kannada',     'उत्तर कन्नड'),
(11, 'Vijayapura',         'विजयपुरा'),
(11, 'Vijayanagara',       'विजयनगर'),
(11, 'Yadgir',             'यादगीर');

-- 12. Kerala (14 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(12, 'Alappuzha',          'अलाप्पुझा'),
(12, 'Ernakulam',          'एर्नाकुलम'),
(12, 'Idukki',             'इडुक्की'),
(12, 'Kannur',             'कन्नूर'),
(12, 'Kasaragod',          'कासरगोड'),
(12, 'Kollam',             'कोल्लम'),
(12, 'Kottayam',           'कोट्टायम'),
(12, 'Kozhikode',          'कोझिकोड'),
(12, 'Malappuram',         'मलप्पुरम'),
(12, 'Palakkad',           'पलक्काड'),
(12, 'Pathanamthitta',     'पथानामथिट्टा'),
(12, 'Thiruvananthapuram', 'तिरुवनंतपुरम'),
(12, 'Thrissur',           'त्रिशूर'),
(12, 'Wayanad',            'वायनाड');

-- 13. Madhya Pradesh (52 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(13, 'Agar Malwa',     'आगर मालवा'),
(13, 'Alirajpur',      'अलीराजपुर'),
(13, 'Anuppur',        'अनूपपुर'),
(13, 'Ashoknagar',     'अशोकनगर'),
(13, 'Balaghat',       'बालाघाट'),
(13, 'Barwani',        'बड़वानी'),
(13, 'Betul',          'बैतूल'),
(13, 'Bhind',          'भिंड'),
(13, 'Bhopal',         'भोपाल'),
(13, 'Burhanpur',      'बुरहानपुर'),
(13, 'Chhatarpur',     'छतरपुर'),
(13, 'Chhindwara',     'छिंदवाड़ा'),
(13, 'Damoh',          'दमोह'),
(13, 'Datia',          'दतिया'),
(13, 'Dewas',          'देवास'),
(13, 'Dhar',           'धार'),
(13, 'Dindori',        'डिंडोरी'),
(13, 'Guna',           'गुना'),
(13, 'Gwalior',        'ग्वालियर'),
(13, 'Harda',          'हरदा'),
(13, 'Indore',         'इंदौर'),
(13, 'Jabalpur',       'जबलपुर'),
(13, 'Jhabua',         'झाबुआ'),
(13, 'Katni',          'कटनी'),
(13, 'Khandwa',        'खंडवा'),
(13, 'Khargone',       'खरगोन'),
(13, 'Maihar',         'मैहर'),
(13, 'Mandla',         'मंडला'),
(13, 'Mandsaur',       'मंदसौर'),
(13, 'Mauganj',        'मऊगंज'),
(13, 'Morena',         'मुरैना'),
(13, 'Narsinghpur',    'नरसिंहपुर'),
(13, 'Niwari',         'निवाड़ी'),
(13, 'Panna',          'पन्ना'),
(13, 'Raisen',         'रायसेन'),
(13, 'Rajgarh',        'राजगढ़'),
(13, 'Ratlam',         'रतलाम'),
(13, 'Rewa',           'रीवा'),
(13, 'Sagar',          'सागर'),
(13, 'Satna',          'सतना'),
(13, 'Sehore',         'सीहोर'),
(13, 'Seoni',          'सिवनी'),
(13, 'Shahdol',        'शहडोल'),
(13, 'Shajapur',       'शाजापुर'),
(13, 'Sheopur',        'श्योपुर'),
(13, 'Shivpuri',       'शिवपुरी'),
(13, 'Sidhi',          'सीधी'),
(13, 'Singrauli',      'सिंगरौली'),
(13, 'Tikamgarh',      'टीकमगढ़'),
(13, 'Ujjain',         'उज्जैन'),
(13, 'Umaria',         'उमरिया'),
(13, 'Vidisha',        'विदिशा');

-- 14. Maharashtra (36 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(14, 'Ahmednagar',        'अहमदनगर'),
(14, 'Akola',             'अकोला'),
(14, 'Amravati',          'अमरावती'),
(14, 'Aurangabad',        'औरंगाबाद'),
(14, 'Beed',              'बीड'),
(14, 'Bhandara',          'भंडारा'),
(14, 'Buldhana',          'बुलडाणा'),
(14, 'Chandrapur',        'चंद्रपुर'),
(14, 'Dhule',             'धुले'),
(14, 'Gadchiroli',        'गडचिरोली'),
(14, 'Gondia',            'गोंदिया'),
(14, 'Hingoli',           'हिंगोली'),
(14, 'Jalgaon',           'जलगांव'),
(14, 'Jalna',             'जालना'),
(14, 'Kolhapur',          'कोल्हापुर'),
(14, 'Latur',             'लातूर'),
(14, 'Mumbai City',       'मुंबई शहर'),
(14, 'Mumbai Suburban',   'मुंबई उपनगर'),
(14, 'Nagpur',            'नागपुर'),
(14, 'Nanded',            'नांदेड'),
(14, 'Nandurbar',         'नंदुरबार'),
(14, 'Nashik',            'नासिक'),
(14, 'Osmanabad',         'उस्मानाबाद'),
(14, 'Palghar',           'पालघर'),
(14, 'Parbhani',          'परभणी'),
(14, 'Pune',              'पुणे'),
(14, 'Raigad',            'रायगड'),
(14, 'Ratnagiri',         'रत्नागिरी'),
(14, 'Sangli',            'सांगली'),
(14, 'Satara',            'सातारा'),
(14, 'Sindhudurg',        'सिंधुदुर्ग'),
(14, 'Solapur',           'सोलापुर'),
(14, 'Thane',             'ठाणे'),
(14, 'Wardha',            'वर्धा'),
(14, 'Washim',            'वाशिम'),
(14, 'Yavatmal',          'यवतमाल');

-- 15. Manipur (16 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(15, 'Bishnupur',     'बिष्णुपुर'),
(15, 'Chandel',       'चंदेल'),
(15, 'Churachandpur', 'चुराचांदपुर'),
(15, 'Imphal East',   'इम्फाल पूर्व'),
(15, 'Imphal West',   'इम्फाल पश्चिम'),
(15, 'Jiribam',       'जिरीबाम'),
(15, 'Kakching',      'काकचिंग'),
(15, 'Kamjong',       'कामजोंग'),
(15, 'Kangpokpi',     'कांगपोकपी'),
(15, 'Noney',         'नोने'),
(15, 'Pherzawl',      'फेरजावल'),
(15, 'Senapati',      'सेनापति'),
(15, 'Tamenglong',    'तामेंगलोंग'),
(15, 'Tengnoupal',    'तेंग्नौपल'),
(15, 'Thoubal',       'थौबल'),
(15, 'Ukhrul',        'उखरुल');

-- 16. Meghalaya (12 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(16, 'East Garo Hills',         'पूर्वी गारो हिल्स'),
(16, 'East Jaintia Hills',      'पूर्वी जयंतिया हिल्स'),
(16, 'East Khasi Hills',        'पूर्वी खासी हिल्स'),
(16, 'Eastern West Khasi Hills','पूर्वी पश्चिम खासी हिल्स'),
(16, 'North Garo Hills',        'उत्तर गारो हिल्स'),
(16, 'Ri Bhoi',                 'री भोई'),
(16, 'South Garo Hills',        'दक्षिण गारो हिल्स'),
(16, 'South West Garo Hills',   'दक्षिण पश्चिम गारो हिल्स'),
(16, 'South West Khasi Hills',  'दक्षिण पश्चिम खासी हिल्स'),
(16, 'West Garo Hills',         'पश्चिमी गारो हिल्स'),
(16, 'West Jaintia Hills',      'पश्चिमी जयंतिया हिल्स'),
(16, 'West Khasi Hills',        'पश्चिमी खासी हिल्स');

-- 17. Mizoram (11 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(17, 'Aizawl',    'आइजोल'),
(17, 'Champhai',  'चम्फाई'),
(17, 'Hnahthial', 'हनहथियल'),
(17, 'Khawzawl',  'खावजॉल'),
(17, 'Kolasib',   'कोलासिब'),
(17, 'Lawngtlai', 'लॉन्गटलाई'),
(17, 'Lunglei',   'लुंगलेई'),
(17, 'Mamit',     'ममित'),
(17, 'Saiha',     'साइहा'),
(17, 'Saitual',   'साइतुअल'),
(17, 'Serchhip',  'सेरछिप');

-- 18. Nagaland (16 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(18, 'Chumoukedima', 'चुमौकेदिमा'),
(18, 'Dimapur',      'दीमापुर'),
(18, 'Kiphire',      'किफिरे'),
(18, 'Kohima',       'कोहिमा'),
(18, 'Longleng',     'लोंगलेंग'),
(18, 'Mokokchung',   'मोकोकचुंग'),
(18, 'Mon',          'मोन'),
(18, 'Niuland',      'नियुलैंड'),
(18, 'Noklak',       'नोक्लाक'),
(18, 'Peren',        'पेरेन'),
(18, 'Phek',         'फेक'),
(18, 'Shamator',     'शमातोर'),
(18, 'Tseminyu',     'सेमिन्यू'),
(18, 'Tuensang',     'त्वेनसांग'),
(18, 'Wokha',        'वोखा'),
(18, 'Zunheboto',    'जुन्हेबोटो');

-- 19. Odisha (30 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(19, 'Angul',          'अंगुल'),
(19, 'Balangir',       'बलांगीर'),
(19, 'Balasore',       'बालेश्वर'),
(19, 'Bargarh',        'बरगढ़'),
(19, 'Bhadrak',        'भद्रक'),
(19, 'Boudh',          'बौद्ध'),
(19, 'Cuttack',        'कटक'),
(19, 'Deogarh',        'देवगढ़'),
(19, 'Dhenkanal',      'ढेंकानाल'),
(19, 'Gajapati',       'गजपति'),
(19, 'Ganjam',         'गंजाम'),
(19, 'Jagatsinghpur',  'जगतसिंहपुर'),
(19, 'Jajpur',         'जाजपुर'),
(19, 'Jharsuguda',     'झारसुगुड़ा'),
(19, 'Kalahandi',      'कालाहांडी'),
(19, 'Kandhamal',      'कंधमाल'),
(19, 'Kendrapara',     'केंद्रापड़ा'),
(19, 'Kendujhar',      'केंदुझर'),
(19, 'Khordha',        'खुर्दा'),
(19, 'Koraput',        'कोरापुट'),
(19, 'Malkangiri',     'मालकानगिरि'),
(19, 'Mayurbhanj',     'मयूरभंज'),
(19, 'Nabarangapur',   'नबरंगपुर'),
(19, 'Nayagarh',       'नयागढ़'),
(19, 'Nuapada',        'नुआपड़ा'),
(19, 'Puri',           'पुरी'),
(19, 'Rayagada',       'रायगडा'),
(19, 'Sambalpur',      'संबलपुर'),
(19, 'Sonepur',        'सोनपुर'),
(19, 'Sundargarh',     'सुंदरगढ़');

-- 20. Punjab (23 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(20, 'Amritsar',                   'अमृतसर'),
(20, 'Barnala',                    'बरनाला'),
(20, 'Bathinda',                   'बठिंडा'),
(20, 'Faridkot',                   'फरीदकोट'),
(20, 'Fatehgarh Sahib',            'फतेहगढ़ साहिब'),
(20, 'Fazilka',                    'फाजिल्का'),
(20, 'Ferozepur',                  'फिरोजपुर'),
(20, 'Gurdaspur',                  'गुरदासपुर'),
(20, 'Hoshiarpur',                 'होशियारपुर'),
(20, 'Jalandhar',                  'जालंधर'),
(20, 'Kapurthala',                 'कपूरथला'),
(20, 'Ludhiana',                   'लुधियाना'),
(20, 'Malerkotla',                 'मलेरकोटला'),
(20, 'Mansa',                      'मानसा'),
(20, 'Moga',                       'मोगा'),
(20, 'Mohali',                     'मोहाली'),
(20, 'Muktsar',                    'मुक्तसर'),
(20, 'Pathankot',                  'पठानकोट'),
(20, 'Patiala',                    'पटियाला'),
(20, 'Rupnagar',                   'रूपनगर'),
(20, 'Sangrur',                    'संगरूर'),
(20, 'Shaheed Bhagat Singh Nagar', 'शहीद भगत सिंह नगर'),
(20, 'Tarn Taran',                 'तरन तारन');

-- 21. Rajasthan (33 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(21, 'Ajmer',           'अजमेर'),
(21, 'Alwar',           'अलवर'),
(21, 'Banswara',        'बांसवाड़ा'),
(21, 'Baran',           'बारां'),
(21, 'Barmer',          'बाड़मेर'),
(21, 'Bharatpur',       'भरतपुर'),
(21, 'Bhilwara',        'भीलवाड़ा'),
(21, 'Bikaner',         'बीकानेर'),
(21, 'Bundi',           'बूंदी'),
(21, 'Chittorgarh',     'चित्तौड़गढ़'),
(21, 'Churu',           'चूरू'),
(21, 'Dausa',           'दौसा'),
(21, 'Dholpur',         'धौलपुर'),
(21, 'Dungarpur',       'डूंगरपुर'),
(21, 'Hanumangarh',     'हनुमानगढ़'),
(21, 'Jaipur',          'जयपुर'),
(21, 'Jaisalmer',       'जैसलमेर'),
(21, 'Jalore',          'जालोर'),
(21, 'Jhalawar',        'झालावाड़'),
(21, 'Jhunjhunu',       'झुंझुनू'),
(21, 'Jodhpur',         'जोधपुर'),
(21, 'Karauli',         'करौली'),
(21, 'Kota',            'कोटा'),
(21, 'Nagaur',          'नागौर'),
(21, 'Pali',            'पाली'),
(21, 'Pratapgarh',      'प्रतापगढ़'),
(21, 'Rajsamand',       'राजसमंद'),
(21, 'Sawai Madhopur',  'सवाई माधोपुर'),
(21, 'Sikar',           'सीकर'),
(21, 'Sirohi',          'सिरोही'),
(21, 'Sri Ganganagar',  'श्रीगंगानगर'),
(21, 'Tonk',            'टोंक'),
(21, 'Udaipur',         'उदयपुर');

-- 22. Sikkim (4 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(22, 'East Sikkim',  'पूर्वी सिक्किम'),
(22, 'North Sikkim', 'उत्तरी सिक्किम'),
(22, 'South Sikkim', 'दक्षिणी सिक्किम'),
(22, 'West Sikkim',  'पश्चिमी सिक्किम');

-- 23. Tamil Nadu (38 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(23, 'Ariyalur',         'अरियलूर'),
(23, 'Chengalpattu',     'चेंगलपट्टू'),
(23, 'Chennai',          'चेन्नई'),
(23, 'Coimbatore',       'कोयंबटूर'),
(23, 'Cuddalore',        'कड्डलोर'),
(23, 'Dharmapuri',       'धर्मपुरी'),
(23, 'Dindigul',         'डिंडीगुल'),
(23, 'Erode',            'इरोड'),
(23, 'Kallakurichi',     'कल्लाकुरिची'),
(23, 'Kanchipuram',      'कांचीपुरम'),
(23, 'Kanyakumari',      'कन्याकुमारी'),
(23, 'Karur',            'करूर'),
(23, 'Krishnagiri',      'कृष्णागिरि'),
(23, 'Madurai',          'मदुरै'),
(23, 'Mayiladuthurai',   'मयिलादुतुरै'),
(23, 'Nagapattinam',     'नागपट्टिनम'),
(23, 'Namakkal',         'नमक्कल'),
(23, 'Nilgiris',         'नीलगिरी'),
(23, 'Perambalur',       'पेरम्बलूर'),
(23, 'Pudukkottai',      'पुदुक्कोट्टई'),
(23, 'Ramanathapuram',   'रामनाथपुरम'),
(23, 'Ranipet',          'रानीपेट'),
(23, 'Salem',            'सेलम'),
(23, 'Sivaganga',        'शिवगंगा'),
(23, 'Tenkasi',          'तेनकासी'),
(23, 'Thanjavur',        'तंजावुर'),
(23, 'Theni',            'थेनी'),
(23, 'Thoothukudi',      'तूतुकुडी'),
(23, 'Tiruchirappalli',  'तिरुचिरापल्ली'),
(23, 'Tirunelveli',      'तिरुनेलवेली'),
(23, 'Tirupathur',       'तिरुपत्तूर'),
(23, 'Tiruppur',         'तिरुपुर'),
(23, 'Tiruvallur',       'तिरुवल्लूर'),
(23, 'Tiruvannamalai',   'तिरुवन्नामलाई'),
(23, 'Tiruvarur',        'तिरुवरूर'),
(23, 'Vellore',          'वेल्लोर'),
(23, 'Villupuram',       'विल्लुपुरम'),
(23, 'Virudhunagar',     'विरुधुनगर');

-- 24. Telangana (33 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(24, 'Adilabad',                 'आदिलाबाद'),
(24, 'Bhadradri Kothagudem',     'भद्राद्री कोठागुडेम'),
(24, 'Hanumakonda',              'हनुमाकोंडा'),
(24, 'Hyderabad',                'हैदराबाद'),
(24, 'Jagtial',                  'जगतियाल'),
(24, 'Jangaon',                  'जनगांव'),
(24, 'Jayashankar Bhupalpally',  'जयशंकर भूपलपल्ली'),
(24, 'Jogulamba Gadwal',         'जोगुलांबा गडवाल'),
(24, 'Kamareddy',                'कामारेड्डी'),
(24, 'Karimnagar',               'करीमनगर'),
(24, 'Khammam',                  'खम्मम'),
(24, 'Komaram Bheem',            'कोमराम भीम'),
(24, 'Mahabubabad',              'महबूबाबाद'),
(24, 'Mahbubnagar',              'महबूबनगर'),
(24, 'Mancherial',               'मंचेरियल'),
(24, 'Medak',                    'मेडक'),
(24, 'Medchal-Malkajgiri',       'मेडचल-मल्काजगिरि'),
(24, 'Mulugu',                   'मुलुगु'),
(24, 'Nagarkurnool',             'नगरकुर्नूल'),
(24, 'Nalgonda',                 'नलगोंडा'),
(24, 'Narayanpet',               'नारायणपेट'),
(24, 'Nirmal',                   'निर्मल'),
(24, 'Nizamabad',                'निजामाबाद'),
(24, 'Peddapalli',               'पेद्दापल्ली'),
(24, 'Rajanna Sircilla',         'राजन्ना सिरसिल्ला'),
(24, 'Rangareddy',               'रंगारेड्डी'),
(24, 'Sangareddy',               'संगारेड्डी'),
(24, 'Siddipet',                 'सिद्दीपेट'),
(24, 'Suryapet',                 'सूर्यापेट'),
(24, 'Vikarabad',                'विकाराबाद'),
(24, 'Wanaparthy',               'वानापर्थी'),
(24, 'Warangal',                 'वारंगल'),
(24, 'Yadadri Bhuvanagiri',      'यदाद्री भुवनगिरि');

-- 25. Tripura (8 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(25, 'Dhalai',       'धलाई'),
(25, 'Gomati',       'गोमती'),
(25, 'Khowai',       'खोवाई'),
(25, 'North Tripura','उत्तर त्रिपुरा'),
(25, 'Sepahijala',   'सेपाहीजाला'),
(25, 'South Tripura','दक्षिण त्रिपुरा'),
(25, 'Unakoti',      'उनाकोटि'),
(25, 'West Tripura', 'पश्चिम त्रिपुरा');

-- 26. Uttar Pradesh (75 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(26, 'Agra',                 'आगरा'),
(26, 'Aligarh',              'अलीगढ़'),
(26, 'Ambedkar Nagar',       'अंबेडकर नगर'),
(26, 'Amethi',               'अमेठी'),
(26, 'Amroha',               'अमरोहा'),
(26, 'Auraiya',              'औरैया'),
(26, 'Ayodhya',              'अयोध्या'),
(26, 'Azamgarh',             'आजमगढ़'),
(26, 'Baghpat',              'बागपत'),
(26, 'Bahraich',             'बहराइच'),
(26, 'Ballia',               'बलिया'),
(26, 'Balrampur',            'बलरामपुर'),
(26, 'Banda',                'बांदा'),
(26, 'Barabanki',            'बाराबंकी'),
(26, 'Bareilly',             'बरेली'),
(26, 'Basti',                'बस्ती'),
(26, 'Bhadohi',              'भदोही'),
(26, 'Bijnor',               'बिजनौर'),
(26, 'Budaun',               'बदायूं'),
(26, 'Bulandshahr',          'बुलंदशहर'),
(26, 'Chandauli',            'चंदौली'),
(26, 'Chitrakoot',           'चित्रकूट'),
(26, 'Deoria',               'देवरिया'),
(26, 'Etah',                 'एटा'),
(26, 'Etawah',               'इटावा'),
(26, 'Farrukhabad',          'फर्रुखाबाद'),
(26, 'Fatehpur',             'फतेहपुर'),
(26, 'Firozabad',            'फिरोजाबाद'),
(26, 'Gautam Buddh Nagar',   'गौतम बुद्ध नगर'),
(26, 'Ghaziabad',            'गाजियाबाद'),
(26, 'Ghazipur',             'गाजीपुर'),
(26, 'Gonda',                'गोंडा'),
(26, 'Gorakhpur',            'गोरखपुर'),
(26, 'Hamirpur',             'हमीरपुर'),
(26, 'Hapur',                'हापुड़'),
(26, 'Hardoi',               'हरदोई'),
(26, 'Hathras',              'हाथरस'),
(26, 'Jalaun',               'जालौन'),
(26, 'Jaunpur',              'जौनपुर'),
(26, 'Jhansi',               'झांसी'),
(26, 'Kannauj',              'कन्नौज'),
(26, 'Kanpur Dehat',         'कानपुर देहात'),
(26, 'Kanpur Nagar',         'कानपुर नगर'),
(26, 'Kasganj',              'कासगंज'),
(26, 'Kaushambi',            'कौशांबी'),
(26, 'Kushinagar',           'कुशीनगर'),
(26, 'Lakhimpur Kheri',      'लखीमपुर खीरी'),
(26, 'Lalitpur',             'ललितपुर'),
(26, 'Lucknow',              'लखनऊ'),
(26, 'Mahoba',               'महोबा'),
(26, 'Mahrajganj',           'महराजगंज'),
(26, 'Mainpuri',             'मैनपुरी'),
(26, 'Mathura',              'मथुरा'),
(26, 'Mau',                  'मऊ'),
(26, 'Meerut',               'मेरठ'),
(26, 'Mirzapur',             'मिर्जापुर'),
(26, 'Moradabad',            'मुरादाबाद'),
(26, 'Muzaffarnagar',        'मुजफ्फरनगर'),
(26, 'Pilibhit',             'पीलीभीत'),
(26, 'Pratapgarh',           'प्रतापगढ़'),
(26, 'Prayagraj',            'प्रयागराज'),
(26, 'Raebareli',            'रायबरेली'),
(26, 'Rampur',               'रामपुर'),
(26, 'Saharanpur',           'सहारनपुर'),
(26, 'Sambhal',              'संभल'),
(26, 'Sant Kabir Nagar',     'संत कबीर नगर'),
(26, 'Shahjahanpur',         'शाहजहांपुर'),
(26, 'Shamli',               'शामली'),
(26, 'Shravasti',            'श्रावस्ती'),
(26, 'Siddharthnagar',       'सिद्धार्थनगर'),
(26, 'Sitapur',              'सीतापुर'),
(26, 'Sonbhadra',            'सोनभद्र'),
(26, 'Sultanpur',            'सुलतानपुर'),
(26, 'Unnao',                'उन्नाव'),
(26, 'Varanasi',             'वाराणसी');

-- 27. Uttarakhand (13 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(27, 'Almora',           'अल्मोड़ा'),
(27, 'Bageshwar',        'बागेश्वर'),
(27, 'Chamoli',          'चमोली'),
(27, 'Champawat',        'चंपावत'),
(27, 'Dehradun',         'देहरादून'),
(27, 'Haridwar',         'हरिद्वार'),
(27, 'Nainital',         'नैनीताल'),
(27, 'Pauri Garhwal',    'पौड़ी गढ़वाल'),
(27, 'Pithoragarh',      'पिथौरागढ़'),
(27, 'Rudraprayag',      'रुद्रप्रयाग'),
(27, 'Tehri Garhwal',    'टिहरी गढ़वाल'),
(27, 'Udham Singh Nagar','उधम सिंह नगर'),
(27, 'Uttarkashi',       'उत्तरकाशी');

-- 28. West Bengal (23 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(28, 'Alipurduar',          'अलीपुरद्वार'),
(28, 'Bankura',             'बांकुड़ा'),
(28, 'Birbhum',             'बीरभूम'),
(28, 'Cooch Behar',         'कूचबिहार'),
(28, 'Dakshin Dinajpur',    'दक्षिण दिनाजपुर'),
(28, 'Darjeeling',          'दार्जिलिंग'),
(28, 'Hooghly',             'हुगली'),
(28, 'Howrah',              'हावड़ा'),
(28, 'Jalpaiguri',          'जलपाईगुड़ी'),
(28, 'Jhargram',            'झाड़ग्राम'),
(28, 'Kalimpong',           'कालिम्पोंग'),
(28, 'Kolkata',             'कोलकाता'),
(28, 'Malda',               'मालदा'),
(28, 'Murshidabad',         'मुर्शिदाबाद'),
(28, 'Nadia',               'नदिया'),
(28, 'North 24 Parganas',   'उत्तर 24 परगना'),
(28, 'Paschim Bardhaman',   'पश्चिम बर्धमान'),
(28, 'Paschim Medinipur',   'पश्चिम मेदिनीपुर'),
(28, 'Purba Bardhaman',     'पूर्व बर्धमान'),
(28, 'Purba Medinipur',     'पूर्व मेदिनीपुर'),
(28, 'Purulia',             'पुरुलिया'),
(28, 'South 24 Parganas',   'दक्षिण 24 परगना'),
(28, 'Uttar Dinajpur',      'उत्तर दिनाजपुर');

-- ── Union Territories ─────────────────────────────────────────────────────────

-- 29. Andaman and Nicobar Islands (3 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(29, 'Nicobar',                  'निकोबार'),
(29, 'North and Middle Andaman', 'उत्तर और मध्य अंडमान'),
(29, 'South Andaman',            'दक्षिण अंडमान');

-- 30. Chandigarh (1 district)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(30, 'Chandigarh', 'चंडीगढ़');

-- 31. Dadra and Nagar Haveli and Daman and Diu (3 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(31, 'Dadra and Nagar Haveli', 'दादरा और नगर हवेली'),
(31, 'Daman',                  'दमन'),
(31, 'Diu',                    'दीव');

-- 32. Delhi (11 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(32, 'Central Delhi',     'मध्य दिल्ली'),
(32, 'East Delhi',        'पूर्वी दिल्ली'),
(32, 'New Delhi',         'नई दिल्ली'),
(32, 'North Delhi',       'उत्तरी दिल्ली'),
(32, 'North East Delhi',  'उत्तर पूर्वी दिल्ली'),
(32, 'North West Delhi',  'उत्तर पश्चिमी दिल्ली'),
(32, 'Shahdara',          'शाहदरा'),
(32, 'South Delhi',       'दक्षिणी दिल्ली'),
(32, 'South East Delhi',  'दक्षिण पूर्वी दिल्ली'),
(32, 'South West Delhi',  'दक्षिण पश्चिमी दिल्ली'),
(32, 'West Delhi',        'पश्चिमी दिल्ली');

-- 33. Jammu and Kashmir (20 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(33, 'Anantnag',   'अनंतनाग'),
(33, 'Bandipora',  'बांडीपोरा'),
(33, 'Baramulla',  'बारामूला'),
(33, 'Budgam',     'बडगाम'),
(33, 'Doda',       'डोडा'),
(33, 'Ganderbal',  'गांदरबल'),
(33, 'Jammu',      'जम्मू'),
(33, 'Kathua',     'कठुआ'),
(33, 'Kishtwar',   'किश्तवाड़'),
(33, 'Kulgam',     'कुलगाम'),
(33, 'Kupwara',    'कुपवाड़ा'),
(33, 'Poonch',     'पुंछ'),
(33, 'Pulwama',    'पुलवामा'),
(33, 'Rajouri',    'राजौरी'),
(33, 'Ramban',     'रामबन'),
(33, 'Reasi',      'रियासी'),
(33, 'Samba',      'सांबा'),
(33, 'Shopian',    'शोपियां'),
(33, 'Srinagar',   'श्रीनगर'),
(33, 'Udhampur',   'उधमपुर');

-- 34. Ladakh (2 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(34, 'Kargil', 'कारगिल'),
(34, 'Leh',    'लेह');

-- 35. Lakshadweep (1 district)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(35, 'Lakshadweep', 'लक्षद्वीप');

-- 36. Puducherry (4 districts)
INSERT INTO geo_districts (state_id, name_en, name_hi) VALUES
(36, 'Karaikal',   'कारैकल'),
(36, 'Mahe',       'माहे'),
(36, 'Puducherry', 'पुदुच्चेरी'),
(36, 'Yanam',      'यानम');
